# Generated by Django 5.0.4 on 2024-04-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="name",
            new_name="fullname",
        ),
        migrations.AddField(
            model_name="user",
            name="onboardingpass",
            field=models.BooleanField(default=False),
        ),
    ]
