# Generated by Django 5.0.4 on 2024-04-14 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_rename_name_user_fullname_user_onboardingpass"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="articles",
            field=models.TextField(default=None),
        ),
    ]
