# Generated by Django 5.0.4 on 2024-04-14 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_articles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="articles",
            field=models.TextField(null=True),
        ),
    ]
