# Generated by Django 5.0.4 on 2024-04-14 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_articles"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="roadmap",
            field=models.TextField(null=True),
        ),
    ]
